[package]
name = "grp_explorer_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
eframe = "0.19.0"
egui = "0.19.0"
id_tree = "1.8.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
rfd = "0.10.0"
strum_macros = "0.24"
font-loader = "0.11.0"

[dependencies.strum]
version = "0.24.1"
features = ["derive"]
